### ISSUE TITLE
《计算机视觉实战演练：算法与应用》GitHub开源中文电子书、源码、读者交流社区

### ISSUE THREAD

**Issue by Charmve** [josephmisiti/awesome-machine-learning#809]
this repo is so awesome, including a wide variety of machine learning treasures. 

in order to complete this repo to become more excellent open source, I'd like to introduce this [*Computer Vision in Action*](https://github.com/Charmve/computer-vision-in-action)(only Chinese now).

L0CV is a new generation of computer vision open source online learning media, a cross-platform interactive learning framework integrating graphics, source code and HTML. the L0CV ecosystem — Notebook, Datasets, Source Code, and from Diving-in to Advanced — as well as the L0CV Hub.

![image](https://user-images.githubusercontent.com/29084184/131811290-e2e8e1db-2374-43f1-9578-1f2cd82de973.png)

- 📕 online book https://charmve.github.io/computer-vision-in-action
- :octocat: GitHub https://github.com/Charmve/computer-vision-in-action

Thanks.

**Comment by bryan-yin** [comment]
thanks for your sharing. it's really good content.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "josephmisiti/awesome-machine-learning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月2日(星期四) 下午5:03
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[josephmisiti/awesome-machine-learning] 《计算机视觉实战演练：算法与应用》GitHub开源中文电子书、源码、读者交流社区 (#809)





 
this repo is so awesome, including a wide variety of machine learning treasures.
 
in order to complete this repo to become more excellent open source, I'd like to introduce this Computer Vision in Action(only Chinese now).
 

 
Thanks.
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by josephmisiti** [comment]
please send in a PR
